name: hayaproject
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.




dependencies:
  smooth_page_indicator: ^1.1.0
  geolocator: ^10.0.1
  meta: ^1.7.0
  flutter_rating_bar: ^4.0.1
  syncfusion_flutter_gauges: ^22.1.39
  get: ^4.6.5
  flutter_plugin_android_lifecycle: ^2.0.0 
  page_transition: ^2.0.9
  auto_size_text: ^3.0.0
  dropdown_button2: ^2.3.7
  font_awesome_flutter: ^10.5.0
  numberpicker: ^2.1.2
  bottom_picker: ^2.0.4
  flutter_cupertino_date_picker_fork: ^1.0.7
  multiselect: ^0.1.0
  flutter_material_pickers: ^3.3.0
  animated_text_kit: ^4.2.2
  flutter_inset_box_shadow: ^1.0.8
  flutter_datetime_picker_bdaya: ^3.0.2
  image_picker: ^1.0.2
  icon_decoration: ^2.0.2
  firebase_auth: ^4.10.0
  awesome_dialog: ^3.1.0
  percent_indicator: ^4.2.3
  http: ^0.13.5




  local_hero: ^0.2.0
  lottie: ^2.6.0


  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  fl_chart: ^0.64.0
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  firebase_storage: ^11.2.7
  firebase_messaging: ^14.6.8
  flutter_speed_dial: ^7.0.0
  sleek_circular_slider: ^2.0.1
  open_street_map_search_and_pick: ^0.1.0
  scrollable_positioned_list: ^0.3.8
  shimmer: ^3.0.0
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.1
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  multi_dropdown: ^2.0.0
  flutter_keyboard_visibility: ^6.0.0
  fluttertoast: ^8.2.4
  cached_network_image: ^3.3.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/mipmap-mdpi/ic_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - Images/
    - Images/wait.jpg
    - asset/Images Food/1.png
    - asset/asset Images Rand/Subtract back.png
    - asset/asset Images Rand/Subtract front.png
    - asset/asset Images Rand/Colored.png
    - asset/Images Food/2.png
    - asset/Images Food/3.png
    - asset/Images Food/4.png
    - FoodImages/
    - Images/White.png
    - Images/basketball.png
    - Images/clouds.png
    - Images/Colored.png
    - Images/cross.png
    - Images/degree.png
    - Images/Football.png
    - Images/hiking.png
    - Images/Login.png
    - Images/pdfimages.jpg
    - Images/man.png
    - Images/woman.png
    - Images/White.png
    - Images/recOrange.png
    - Images/recBlue.png
    - Images/Picture2.png
    - Images/ss.png
    - Images/h.png
    - Images/Specialist_Background.png
    - asset/asset Images Rand/FoodBack.png
    - Images/Picture1.png
    - Images/Nutritionist.png
    - Images/marathon2.png
    - Images/marathon1.png
    - Images/Picture2.png
    - Images/Picture1.png
    - Images/Left.png
    - asset/Images/
    - asset/BodyMap/
    - Exercises/
    - asset/BodyMap/
    - asset/Images/Gif/
    - asset/Images/Workout cover/
    - Moreimages/
    - Images/App logo.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: asset/Fonts/MyFlutterApp.ttf
    - family: UbuntuREG
      fonts:
        - asset: asset/Ubuntu-Regular.ttf
    - family: UbuntuBOLD
      fonts:
        - asset: asset/Ubuntu-Bold.ttf
    - family: UbuntuMED
      fonts:
        - asset: asset/Ubuntu-Medium.ttf
    - family: ITC Avant
      fonts:
        - asset: asset/Fonts/ITC.otf